### ISSUE TITLE
Common app for all components with publication and tests config

### ISSUE THREAD

**Issue by tlenclos** [premieroctet/po.components#1]
We need to merge the components demo and publication.

# TODO
- [ ] Setup yarn workspaces https://yarnpkg.com/en/docs/workspaces
- [ ] Add a jest setup to test components
- [ ] Maybe also lerna https://github.com/lerna/lerna or np https://github.com/sindresorhus/np
